/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmCameraBaslerImagePresentation_hpp__
#define __ZcmCameraBaslerImagePresentation_hpp__

#include <string>
#include <vector>


/**
 * =======================================================================================
 * =======================================================================================
 * @struct ZcmCameraBaslerImagePresentation
 * @brief Картинка.
 *
 * @var ZcmCameraBaslerImagePresentation::width
 * @brief ширина.
 * @var ZcmCameraBaslerImagePresentation::height
 * @brief высота.
 * @var ZcmCameraBaslerImagePresentation::data
 * @brief данные картинки.
 *
 * @var ZcmCameraBaslerImagePresentation::bytes_per_line
 * @brief Часто линии картинок выравниваются, переменная указывает какой реальный
 * размер линии используется.
 *
 * @var ZcmCameraBaslerImagePresentation::format
 * @brief Формат задается строкой, но должен содержать фиксированные обозначения: \n
 * Gray_8, RGB_888, BGR_888.
 *
 */
class ZcmCameraBaslerImagePresentation
{
    public:
        int32_t    width;

        int32_t    height;

        int32_t    bytes_per_line;

        std::string format;

        int32_t    data_size;

        std::vector< uint8_t > data;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmCameraBaslerImagePresentation() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmCameraBaslerImagePresentation"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmCameraBaslerImagePresentation::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmCameraBaslerImagePresentation::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmCameraBaslerImagePresentation::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmCameraBaslerImagePresentation::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmCameraBaslerImagePresentation::getTypeName()
{
    return "ZcmCameraBaslerImagePresentation";
}

int ZcmCameraBaslerImagePresentation::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->bytes_per_line, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    char* format_cstr = (char*) this->format.c_str();
    thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &format_cstr, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->data_size, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    if(this->data_size > 0) {
        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->data[0], this->data_size);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    return pos;
}

int ZcmCameraBaslerImagePresentation::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->bytes_per_line, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    int32_t __format_len__;
    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__format_len__, 1);
    if(thislen < 0) return thislen; else pos += thislen;
    if((uint32_t)__format_len__ > maxlen - pos) return -1;
    this->format.assign(((const char*)buf) + offset + pos, __format_len__ - 1);
    pos += __format_len__;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->data_size, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    if(this->data_size > 0) {
        this->data.resize(this->data_size);
        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->data[0], this->data_size);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    return pos;
}

uint32_t ZcmCameraBaslerImagePresentation::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->format.size() + 4 + 1;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __byte_encoded_array_size(NULL, this->data_size);
    return enc_size;
}

uint64_t ZcmCameraBaslerImagePresentation::_computeHash(const __zcm_hash_ptr*)
{
    uint64_t hash = (uint64_t)0xd9af91e2fd9d4b64LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
