/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmCameraBaslerJpegFrame_hpp__
#define __ZcmCameraBaslerJpegFrame_hpp__

#include <vector>
#include "ZcmCameraBaslerInformation.hpp"
#include "ZcmService.hpp"


/**
 * =======================================================================================
 * @struct ZcmCameraBaslerJpegFrame
 * @brief Сжатый JPEG-ом кадр от камеры.
 * Обычно это каждый N-ый принятый кадр для долгосрочного хранения.
 *
 *
 * @var ZcmCameraBaslerJpegFrame::synchronized
 * @brief Флаг, подтверждающий попадание фрейма (с небольшой погрешностью) 
 * на "временную сетку".
 *
 * @var ZcmCameraBaslerJpegFrame::timestamp_ns
 * @brief Метка времени, установленная камерой. Если PTP не "прогрелся", будет в
 * районе 70-го года.
 *
 * @var ZcmCameraBaslerJpegFrame::jpeg
 * @brief Сжатые данные. Их можно, например, сохранять в файлы с расширением .jpeg.
 *
 */
class ZcmCameraBaslerJpegFrame
{
    public:
        ZcmCameraBaslerInformation info;

        int8_t     synchronized;

        int64_t    timestamp_ns;

        int32_t    jpeg_size;

        std::vector< uint8_t > jpeg;

        ZcmService service;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmCameraBaslerJpegFrame() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmCameraBaslerJpegFrame"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmCameraBaslerJpegFrame::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmCameraBaslerJpegFrame::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmCameraBaslerJpegFrame::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmCameraBaslerJpegFrame::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmCameraBaslerJpegFrame::getTypeName()
{
    return "ZcmCameraBaslerJpegFrame";
}

int ZcmCameraBaslerJpegFrame::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->info._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->synchronized, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp_ns, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->jpeg_size, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    if(this->jpeg_size > 0) {
        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->jpeg[0], this->jpeg_size);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    thislen = this->service._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmCameraBaslerJpegFrame::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->info._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->synchronized, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp_ns, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->jpeg_size, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    if(this->jpeg_size > 0) {
        this->jpeg.resize(this->jpeg_size);
        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->jpeg[0], this->jpeg_size);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    thislen = this->service._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmCameraBaslerJpegFrame::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->info._getEncodedSizeNoHash();
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __byte_encoded_array_size(NULL, this->jpeg_size);
    enc_size += this->service._getEncodedSizeNoHash();
    return enc_size;
}

uint64_t ZcmCameraBaslerJpegFrame::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmCameraBaslerJpegFrame::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmCameraBaslerJpegFrame::getHash };

    uint64_t hash = (uint64_t)0x1092530b652debfeLL +
         ZcmCameraBaslerInformation::_computeHash(&cp) +
         ZcmService::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
