/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmCameraBaslerInformation_hpp__
#define __ZcmCameraBaslerInformation_hpp__

#include <string>
#include "ZcmCameraCalibratingParams.hpp"


/**
 * =======================================================================================
 * @struct ZcmCameraBaslerInformation
 * @brief  Информация о камере-передатчике.
 *
 *
 * @var   ZcmCameraBaslerInformation::user_defined_name
 * @brief Из PylonIpConfigurator камере может быть присвоено имя, оно и передается.
 *
 * @var   ZcmCameraBaslerInformation::location
 * @brief Передается информация о местонахождении камеры.
 * Предполагаются FrontLeft, FrontRight, RearLeft, RearRight.
 *
 */
class ZcmCameraBaslerInformation
{
    public:
        std::string serial_number;

        std::string user_defined_name;

        ZcmCameraCalibratingParams calibrating_params;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmCameraBaslerInformation() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmCameraBaslerInformation"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmCameraBaslerInformation::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmCameraBaslerInformation::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmCameraBaslerInformation::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmCameraBaslerInformation::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmCameraBaslerInformation::getTypeName()
{
    return "ZcmCameraBaslerInformation";
}

int ZcmCameraBaslerInformation::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    char* serial_number_cstr = (char*) this->serial_number.c_str();
    thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &serial_number_cstr, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    char* user_defined_name_cstr = (char*) this->user_defined_name.c_str();
    thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &user_defined_name_cstr, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->calibrating_params._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmCameraBaslerInformation::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int32_t __serial_number_len__;
    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__serial_number_len__, 1);
    if(thislen < 0) return thislen; else pos += thislen;
    if((uint32_t)__serial_number_len__ > maxlen - pos) return -1;
    this->serial_number.assign(((const char*)buf) + offset + pos, __serial_number_len__ - 1);
    pos += __serial_number_len__;

    int32_t __user_defined_name_len__;
    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__user_defined_name_len__, 1);
    if(thislen < 0) return thislen; else pos += thislen;
    if((uint32_t)__user_defined_name_len__ > maxlen - pos) return -1;
    this->user_defined_name.assign(((const char*)buf) + offset + pos, __user_defined_name_len__ - 1);
    pos += __user_defined_name_len__;

    thislen = this->calibrating_params._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmCameraBaslerInformation::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->serial_number.size() + 4 + 1;
    enc_size += this->user_defined_name.size() + 4 + 1;
    enc_size += this->calibrating_params._getEncodedSizeNoHash();
    return enc_size;
}

uint64_t ZcmCameraBaslerInformation::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmCameraBaslerInformation::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmCameraBaslerInformation::getHash };

    uint64_t hash = (uint64_t)0x665c65ab7d017db6LL +
         ZcmCameraCalibratingParams::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
